// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesManagement.Data;

#nullable disable

namespace SalesManagement.Data.Migrations
{
    [DbContext(typeof(SalesManagementDbContext))]
    partial class SalesManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesManagement.Data.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@electronics.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            Password = "admin123",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "staff@electronics.com",
                            FullName = "Staff Demo",
                            IsActive = true,
                            Password = "staff123",
                            Role = 2
                        });
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Mobile phones and accessories",
                            Name = "Smartphones",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Description = "Notebooks and laptops",
                            Name = "Laptops",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tablets and e-readers",
                            Name = "Tablets",
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            Description = "Electronics accessories",
                            Name = "Accessories",
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            Description = "Speakers, headphones, earbuds",
                            Name = "Audio",
                            Status = true
                        });
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Nguyễn Huệ, Q.1, TP.HCM",
                            CreatedDate = new DateTime(2026, 1, 14, 22, 14, 49, 30, DateTimeKind.Local).AddTicks(6571),
                            Email = "nguyenvana@gmail.com",
                            FullName = "Nguyễn Văn A",
                            Phone = "0901234567",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Lê Lợi, Q.3, TP.HCM",
                            CreatedDate = new DateTime(2026, 1, 14, 22, 14, 49, 30, DateTimeKind.Local).AddTicks(6582),
                            Email = "tranthib@gmail.com",
                            FullName = "Trần Thị B",
                            Phone = "0902345678",
                            Status = true
                        });
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.ImportOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SupplierId");

                    b.ToTable("ImportOrders");
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.ImportOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImportOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ImportOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ImportOrderDetails");
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Code = "IP15PM",
                            Description = "iPhone 15 Pro Max 256GB",
                            ImageUrl = "/images/products/iphone15promax.jpg",
                            Name = "iPhone 15 Pro Max",
                            Price = 32990000m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Code = "SS24U",
                            Description = "Samsung Galaxy S24 Ultra 256GB",
                            ImageUrl = "/images/products/galaxys24ultra.jpg",
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 29990000m,
                            Quantity = 40,
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Code = "MBP14M3",
                            Description = "MacBook Pro 14 inch M3 chip",
                            ImageUrl = "/images/products/macbookpro14.jpg",
                            Name = "MacBook Pro 14 M3",
                            Price = 49990000m,
                            Quantity = 25,
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Code = "IPADPRO12",
                            Description = "iPad Pro 12.9 inch M2 chip",
                            ImageUrl = "/images/products/ipadpro.jpg",
                            Name = "iPad Pro 12.9 M2",
                            Price = 28990000m,
                            Quantity = 30,
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Code = "APP2",
                            Description = "AirPods Pro thế hệ 2",
                            ImageUrl = "/images/products/airpodspro2.jpg",
                            Name = "AirPods Pro 2",
                            Price = 5990000m,
                            Quantity = 100,
                            Status = true
                        });
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Tòa nhà Bitexco, Q.1, TP.HCM",
                            CompanyName = "Apple Vietnam",
                            ContactPhone = "028-1234-5678",
                            Email = "supply@apple.vn",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "KCN Thái Nguyên, Thái Nguyên",
                            CompanyName = "Samsung Electronics Vietnam",
                            ContactPhone = "028-2345-6789",
                            Email = "supply@samsung.vn",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Address = "Q.7, TP.HCM",
                            CompanyName = "Sony Vietnam",
                            ContactPhone = "028-3456-7890",
                            Email = "supply@sony.vn",
                            Status = true
                        });
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.ImportOrder", b =>
                {
                    b.HasOne("SalesManagement.Data.Entities.Account", "CreatedByAccount")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SalesManagement.Data.Entities.Supplier", "Supplier")
                        .WithMany("ImportOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByAccount");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.ImportOrderDetail", b =>
                {
                    b.HasOne("SalesManagement.Data.Entities.ImportOrder", "ImportOrder")
                        .WithMany("ImportOrderDetails")
                        .HasForeignKey("ImportOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesManagement.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.Order", b =>
                {
                    b.HasOne("SalesManagement.Data.Entities.Account", "CreatedByAccount")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SalesManagement.Data.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByAccount");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("SalesManagement.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesManagement.Data.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.Product", b =>
                {
                    b.HasOne("SalesManagement.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.ImportOrder", b =>
                {
                    b.Navigation("ImportOrderDetails");
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("SalesManagement.Data.Entities.Supplier", b =>
                {
                    b.Navigation("ImportOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
